# Generated by Django 4.1.7 on 2023-06-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_arr', models.CharField(max_length=12, unique=True, verbose_name='Rut Arrendatario')),
                ('pri_nom_arr', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('seg_nom_arr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('pri_ape_arr', models.CharField(max_length=50, verbose_name='Primero Apellido')),
                ('seg_ape_arr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('contacto_arr', models.IntegerField(verbose_name='Contacto')),
                ('correo_arr', models.EmailField(max_length=254, verbose_name='Correo')),
                ('estado', models.BooleanField()),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateTimeField(verbose_name='Fecha de Termino')),
                ('dia_pago', models.IntegerField(blank=True, null=True, verbose_name='Día de pago (nro.)')),
                ('comision', models.FloatField(blank=True, null=True, verbose_name='Comisión')),
                ('periodo_reajuste', models.IntegerField(verbose_name='Perdio Reajuste')),
                ('fecha_reajuste', models.DateTimeField(blank=True, null=True)),
                ('valor_arriendo', models.PositiveBigIntegerField(default=0, verbose_name='Valor Arriendo')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega arriendo')),
                ('estado_arriendo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales sobre el arriendo')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.arrendatario')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=180, unique=True, verbose_name='Nombre del Banco')),
                ('cod_banco', models.CharField(max_length=100, unique=True, verbose_name='Código Banco ')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_com', models.CharField(max_length=200, unique=True, verbose_name='Nombre Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='rut externo')),
                ('contacto', models.IntegerField(verbose_name='Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalidadJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=80)),
                ('razon_social', models.CharField(max_length=250, verbose_name='Razón Social')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección Principal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contacto', models.IntegerField(blank=True, null=True, verbose_name='Contacto')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ppdd', models.CharField(max_length=150, verbose_name='Dirección Propiedad')),
                ('numero_ppdd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Propiedad')),
                ('rol_ppdd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol propiedad')),
                ('cod', models.IntegerField(blank=True, null=True, unique=True)),
                ('nro_bodega', models.IntegerField(blank=True, default=None, null=True, verbose_name='Número Bodega')),
                ('nro_estacionamiento', models.IntegerField(blank=True, default=None, null=True, verbose_name='Número Estacionamiento')),
                ('valor_arriendo_base', models.PositiveBigIntegerField(default=0, verbose_name='Valor Arriendo Base')),
                ('es_valor_uf', models.BooleanField(default=False)),
                ('gas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Gas')),
                ('agua', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código ESSBIO')),
                ('luz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Luz')),
                ('incluye_gc', models.BooleanField(default=False)),
                ('valor_gasto_comun', models.PositiveBigIntegerField(default=0)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Región')),
                ('orden', models.IntegerField(default=0, unique=True, verbose_name='orden region')),
                ('nom_reg', models.CharField(max_length=250, unique=True, verbose_name='Nombre Región')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cuenta', models.CharField(max_length=150, verbose_name='Nombre de la cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipoppdd', models.CharField(max_length=150, verbose_name='Tipo de propiedad')),
                ('descripcion_tipoppdd', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ValoresGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trab', models.CharField(max_length=12, unique=True, verbose_name='Rut Trabajador')),
                ('pri_nom_trab', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('seg_nom_trab', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('pri_ape_trab', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('seg_ape_trab', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.comuna')),
                ('tipo_trab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.tipotrabajador', verbose_name='Area Trabajador')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_servicio', models.CharField(max_length=150, verbose_name='Nombre servicio')),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.IntegerField(default=0)),
                ('nro_cuotas', models.PositiveIntegerField(default=1)),
                ('monto_cuotas', models.PositiveBigIntegerField(default=0)),
                ('contador_cuotas', models.PositiveIntegerField(default=0)),
                ('arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.arriendo')),
                ('externo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.externo')),
                ('propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_prop', models.CharField(max_length=12, unique=True, verbose_name='Rut Propietario')),
                ('pri_nom_prop', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('seg_nom_prop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre')),
                ('pri_ape_prop', models.CharField(max_length=50, verbose_name='Primero Apellido')),
                ('seg_ape_prop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('direccion_prop', models.CharField(max_length=200, verbose_name='Dirección Principal')),
                ('email_prop', models.EmailField(max_length=254, verbose_name='Email Propietario')),
                ('contacto_prop', models.IntegerField(verbose_name='Contacto Propietario')),
                ('pctje_cobro_honorario', models.FloatField(default=7, verbose_name='Porcentaje Cobro Propietario')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.comuna')),
                ('personalidad_juridica', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.personalidadjuridica')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.propietario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipopropiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.tipopropiedad'),
        ),
        migrations.CreateModel(
            name='Gastocomun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_a_pagar', models.DateTimeField()),
                ('monto_a_pagar', models.PositiveIntegerField(null=True)),
                ('fecha_pagada', models.DateTimeField(blank=True, default=None, null=True)),
                ('monto_pagado', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_multa', models.PositiveIntegerField(default=0)),
                ('arriendo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.PositiveBigIntegerField(verbose_name='Numero de cuenta')),
                ('estado_cuenta', models.CharField(max_length=100, verbose_name='Estado de cuenta')),
                ('propietario_rut', models.CharField(default='01.234.456-7', max_length=12, verbose_name='Propietario de la cuenta')),
                ('rut_tercero', models.CharField(blank=True, default='11.111.111-1', max_length=12, null=True, verbose_name='Propietario de la cuenta')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.banco')),
                ('tipocuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.tipocuenta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.region'),
        ),
        migrations.CreateModel(
            name='ArriendoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.arriendo')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='arriendo',
            name='externo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.externo'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiArriendosAlegria.propiedad'),
        ),
    ]
