# Generated by Django 4.1.7 on 2023-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='dia_pago',
            field=models.IntegerField(default=5, verbose_name='Día de pago (nro.)'),
        ),
    ]
