# Generated by Django 4.1.7 on 2023-06-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0002_alter_arriendo_dia_pago"),
    ]

    operations = [
        migrations.RemoveField(model_name="serviciosextras", name="arriendo",),
        migrations.RemoveField(model_name="serviciosextras", name="externo",),
        migrations.AddField(
            model_name="propiedad",
            name="externo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ApiArriendosAlegria.externo",
            ),
        ),
    ]
