# Generated by Django 4.1.7 on 2023-06-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0003_remove_serviciosextras_arriendo_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="arriendo", name="externo",),
    ]
