# Generated by Django 4.1.7 on 2023-06-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0004_remove_arriendo_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallearriendo',
            name='arriendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_arriendos', to='ApiArriendosAlegria.arriendo'),
        ),
        migrations.AlterField(
            model_name='serviciosextras',
            name='propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_extras', to='ApiArriendosAlegria.propiedad'),
        ),
        migrations.CreateModel(
            name='CodigoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.PositiveIntegerField(unique=True)),
                ('propiedad', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApiArriendosAlegria.propiedad')),
            ],
        ),
    ]
