# Generated by Django 4.1.7 on 2023-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiArriendosAlegria', '0005_alter_detallearriendo_arriendo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='externo',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales sobre la propiedad'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='periodo_reajuste',
            field=models.IntegerField(verbose_name='Período Reajuste'),
        ),
    ]
