# Generated by Django 4.1.7 on 2023-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApiArriendosAlegria", "0007_detallearriendo_toca_reajuste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallearriendo",
            name="toca_reajuste",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
